# -*- coding: utf-8 -*-
"""
Π(T) — Cost-Benefit Model for NOC-to-SOC Transformation — COMET Framework.

This module computes the Net Present Value (NPV) of the transformation
investment over a time horizon T, accounting for the value generated by
automation (which depends on SGMI) and the ongoing implementation cost.

Mathematical Formulation:
    Π(T) = ∫₀ᵀ [V_auto(SGMI, t) − C_impl(SGMI, t)] · e^{−r·t} dt  −  C₀

where:
    V_auto(SGMI, t) = a · SGMI · (1 − exp(−b · t))
        Value generated by automation at time t. Grows with SGMI and
        saturates over time with rate b.
    C_impl(SGMI, t) = c · SGMI + d
        Implementation cost at time t: a fixed overhead d plus a term
        proportional to SGMI with coefficient c.
    r = discount rate (e.g. 0.08 for 8% annual rate)
    C₀ = initial (upfront) investment cost
    T = evaluation horizon (years)

The integral is computed via Simpson's rule (scipy.integrate.simpson).

References:
    COMET Framework — NOC-to-SOC Unified Theory of Intelligent Service
    Transformation in Telecommunications.
"""

from __future__ import annotations

from typing import Callable, Optional

import numpy as np
from scipy import integrate


def value_auto(
    t: np.ndarray,
    sgmi: float,
    a: float = 10.0,
    b: float = 0.5,
) -> np.ndarray:
    """
    Automation value function V_auto(SGMI, t).

    Parameters
    ----------
    t : np.ndarray
        Time points.
    sgmi : float
        Service Graph Maturity Index.
    a : float
        Value scaling factor (currency units per SGMI unit).
    b : float
        Saturation rate of value growth.

    Returns
    -------
    np.ndarray
        Value at each time point.
    """
    return a * sgmi * (1.0 - np.exp(-b * t))


def cost_impl(
    t: np.ndarray,
    sgmi: float,
    c: float = 2.0,
    d: float = 1.0,
) -> np.ndarray:
    """
    Implementation cost function C_impl(SGMI, t).

    Parameters
    ----------
    t : np.ndarray
        Time points (unused in the base model but kept for signature
        consistency — enables time-varying cost extensions).
    sgmi : float
        Service Graph Maturity Index.
    c : float
        Cost coefficient proportional to SGMI.
    d : float
        Fixed cost overhead.

    Returns
    -------
    np.ndarray
        Cost at each time point (constant over time in base model).
    """
    return (c * sgmi + d) * np.ones_like(t)


def compute_npv(
    sgmi: float,
    t_end: float = 5.0,
    r: float = 0.08,
    c0: float = 50.0,
    a: float = 10.0,
    b: float = 0.5,
    c_cost: float = 2.0,
    d_cost: float = 1.0,
    n_points: int = 1000,
    v_func: Optional[Callable] = None,
    c_func: Optional[Callable] = None,
) -> float:
    """
    Compute the Net Present Value Π(T) of the transformation.

    Parameters
    ----------
    sgmi : float
        Service Graph Maturity Index (assumed constant over horizon).
    t_end : float, optional
        Evaluation horizon T (years). Default is 5.
    r : float, optional
        Discount rate. Default is 0.08 (8%).
    c0 : float, optional
        Upfront investment cost. Default is 50.
    a : float, optional
        Value scaling factor. Default is 10.
    b : float, optional
        Value saturation rate. Default is 0.5.
    c_cost : float, optional
        Cost coefficient for SGMI. Default is 2.
    d_cost : float, optional
        Fixed cost overhead. Default is 1.
    n_points : int, optional
        Number of quadrature points. Default is 1000.
    v_func : callable or None, optional
        Custom value function V(t, sgmi). Signature: f(t, sgmi) → array.
    c_func : callable or None, optional
        Custom cost function C(t, sgmi). Signature: f(t, sgmi) → array.

    Returns
    -------
    float
        Net Present Value Π(T). Positive = investment is worthwhile.

    Raises
    ------
    ValueError
        If t_end ≤ 0, r < 0, c0 < 0, n_points < 2, or sgmi < 0.

    Examples
    --------
    >>> npv = compute_npv(sgmi=0.7, t_end=5.0, r=0.08, c0=50.0)
    """
    if sgmi < 0:
        raise ValueError(f"sgmi must be non-negative, got {sgmi}.")
    if t_end <= 0:
        raise ValueError(f"t_end must be positive, got {t_end}.")
    if r < 0:
        raise ValueError(f"r (discount rate) must be non-negative, got {r}.")
    if c0 < 0:
        raise ValueError(f"c0 (upfront cost) must be non-negative, got {c0}.")
    if n_points < 2:
        raise ValueError(f"n_points must be ≥ 2, got {n_points}.")

    t = np.linspace(0, t_end, n_points)
    discount = np.exp(-r * t)

    if v_func is not None:
        v = np.asarray(v_func(t, sgmi), dtype=np.float64)
    else:
        v = value_auto(t, sgmi, a=a, b=b)

    if c_func is not None:
        c = np.asarray(c_func(t, sgmi), dtype=np.float64)
    else:
        c = cost_impl(t, sgmi, c=c_cost, d=d_cost)

    net_benefit = (v - c) * discount
    integral_value = integrate.simpson(y=net_benefit, x=t)
    npv = integral_value - c0

    return float(npv)


class CostBenefitModel:
    """
    Reusable cost-benefit analysis model.

    Parameters
    ----------
    r : float
        Annual discount rate. Default is 0.08.
    c0 : float
        Upfront investment. Default is 50.
    a, b : float
        Value function parameters. Defaults: a=10, b=0.5.
    c_cost, d_cost : float
        Cost function parameters. Defaults: c=2, d=1.
    """

    def __init__(
        self,
        r: float = 0.08,
        c0: float = 50.0,
        a: float = 10.0,
        b: float = 0.5,
        c_cost: float = 2.0,
        d_cost: float = 1.0,
    ) -> None:
        self.r = r
        self.c0 = c0
        self.a = a
        self.b = b
        self.c_cost = c_cost
        self.d_cost = d_cost

    def npv(
        self,
        sgmi: float,
        t_end: float = 5.0,
        n_points: int = 1000,
    ) -> float:
        """Compute NPV with stored parameters."""
        return compute_npv(
            sgmi=sgmi,
            t_end=t_end,
            r=self.r,
            c0=self.c0,
            a=self.a,
            b=self.b,
            c_cost=self.c_cost,
            d_cost=self.d_cost,
            n_points=n_points,
        )

    def breakeven_sgmi(
        self,
        t_end: float = 5.0,
        n_points: int = 1000,
        tol: float = 1e-4,
    ) -> float | None:
        """
        Find the minimum SGMI at which NPV ≥ 0 (breakeven) via bisection.

        Returns
        -------
        float or None
            Breakeven SGMI, or None if no breakeven exists in [0, 1].
        """
        low, high = 0.0, 1.0

        # Check if even SGMI=1 yields negative NPV
        if self.npv(1.0, t_end, n_points) < 0:
            return None

        # Check if SGMI=0 already positive (unlikely but handle it)
        if self.npv(0.0, t_end, n_points) >= 0:
            return 0.0

        # Bisection search
        while high - low > tol:
            mid = (low + high) / 2.0
            if self.npv(mid, t_end, n_points) < 0:
                low = mid
            else:
                high = mid

        return (low + high) / 2.0


if __name__ == "__main__":
    model = CostBenefitModel(r=0.08, c0=50.0, a=10.0, b=0.5,
                              c_cost=2.0, d_cost=1.0)

    # NPV at various SGMI levels
    print("NPV at different SGMI values (T=5 years, r=8%):")
    for sgmi in [0.3, 0.5, 0.7, 0.9]:
        npv = model.npv(sgmi, t_end=5.0)
        print(f"  SGMI={sgmi:.1f}  →  NPV = {npv:+.2f}")

    # Breakeven analysis
    be = model.breakeven_sgmi(t_end=5.0)
    print(f"\nBreakeven SGMI (T=5y): {be:.4f}" if be is not None
          else "\nNo breakeven SGMI found in [0, 1].")

    # Impact of discount rate
    print(f"\nNPV sensitivity to discount rate (SGMI=0.7, T=5y):")
    for r in [0.0, 0.04, 0.08, 0.12, 0.16]:
        m = CostBenefitModel(r=r, c0=50.0)
        val = m.npv(0.7, t_end=5.0)
        print(f"  r={r:.0%}  →  NPV = {val:+.2f}")